# Use the official Python image as the base image
FROM python:3.9-slim-buster

# Install Python packages from requirements.txt
COPY ./requirements.txt /tmp/
RUN python -m pip install --no-cache-dir -r /tmp/requirements.txt

# Set the working directory
WORKDIR /app

# Add your application code
COPY ./sdr_lab_portal /app

# Expose the Flask port
EXPOSE 8080

# Start your Flask application
CMD flask run --host=0.0.0.0 --port=8080
